ASPECT_KEYWORDS = {
    "food": {"food", "meal", "taste", "dish", "menu", "flavor", "flavour"},
    "service": {"service", "staff", "waiter", "waitress", "response", "support"},
    "price": {"price", "cost", "expensive", "cheap", "affordable", "value"},
    "delivery": {
        "arrived",
        "courier",
        "delivered",
        "delivery",
        "driver",
        "late",
        "package",
        "quick",
        "schedule",
        "shipment",
        "shipping",
        "delay",
    },
    "quality": {"quality", "durable", "poor", "excellent", "defective", "packaging"},
    "ambience": {"ambience", "atmosphere", "environment", "place", "decor"},
}

POSITIVE_WORDS = {
    "amazing",
    "affordable",
    "ahead",
    "best",
    "better",
    "clean",
    "easy",
    "delicious",
    "excellent",
    "fast",
    "friendly",
    "good",
    "great",
    "happy",
    "helpful",
    "improved",
    "love",
    "nice",
    "perfect",
    "pleasant",
    "quick",
    "early",
    "recommended",
    "satisfied",
    "tasty",
    "worth",
}

NEGATIVE_WORDS = {
    "angry",
    "awful",
    "bad",
    "broken",
    "complaint",
    "costly",
    "damaged",
    "delay",
    "defective",
    "disappointed",
    "hate",
    "horrible",
    "expensive",
    "late",
    "problem",
    "poor",
    "rude",
    "slow",
    "terrible",
    "unhappy",
    "useless",
    "waste",
    "worst",
}
